language: python
python:
    - "2.7"
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35

sudo: required
install:
    - pip install -r requirements.txt 
script: >
    tox && 
    python setup.py install && 
    py.test --cov=ngadnap tests
after_success:
    - coveralls
